package main

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"io"
	"net/http"
	"path"
	"strings"
	"sync/atomic"

	"github.com/router-for-me/CLIProxyAPI/v8/sdk/pluginapi"
	"gopkg.in/yaml.v3"
)

const pluginID = "key-chat-access"

// Identity comes from CPA's authenticated caller_scope, never a client header.
// This is the v8.0.4 namespace generated by sdk/cliproxy/session.CallerScope.
type policyConfig struct {
	Enabled             bool     `yaml:"enabled"`
	Priority            int      `yaml:"priority"`
	Store               any      `yaml:"store"`
	BlockedCallerScopes []string `yaml:"blocked_caller_scopes"`
}

type policy struct {
	enabled bool
	blocked map[string]struct{}
}

var activePolicy atomic.Pointer[policy]

func parsePolicy(raw []byte) (*policy, error) {
	cfg := policyConfig{Enabled: true}
	decoder := yaml.NewDecoder(bytes.NewReader(raw))
	decoder.KnownFields(true)
	if err := decoder.Decode(&cfg); err != nil && err != io.EOF {
		return nil, fmt.Errorf("invalid key-chat-access configuration: %w", err)
	}
	var extra any
	if err := decoder.Decode(&extra); err != io.EOF {
		return nil, fmt.Errorf("configuration must contain one YAML document")
	}
	p := &policy{enabled: cfg.Enabled, blocked: make(map[string]struct{}, len(cfg.BlockedCallerScopes))}
	for i, scope := range cfg.BlockedCallerScopes {
		scope = strings.ToLower(strings.TrimSpace(scope))
		decoded, err := hex.DecodeString(scope)
		if err != nil || len(decoded) != 32 {
			return nil, fmt.Errorf("blocked_caller_scopes[%d] must be a 64-character hexadecimal caller scope", i)
		}
		if _, exists := p.blocked[scope]; exists {
			return nil, fmt.Errorf("blocked_caller_scopes contains a duplicate at index %d", i)
		}
		p.blocked[scope] = struct{}{}
	}
	return p, nil
}

func (p *policy) intercept(req pluginapi.RequestInterceptRequest) pluginapi.RequestInterceptResponse {
	if p == nil || !p.enabled || len(p.blocked) == 0 {
		return pluginapi.RequestInterceptResponse{}
	}
	scope, _ := req.Metadata["caller_scope"].(string)
	if _, blocked := p.blocked[scope]; !blocked {
		return pluginapi.RequestInterceptResponse{}
	}
	requestPath, _ := req.Metadata["request_path"].(string)
	// Match the inbound route, not the upstream format: Responses and Messages
	// may also be translated to OpenAI upstreams. Preserve /v1/completions too.
	if path.Clean(requestPath) != "/v1/chat/completions" {
		return pluginapi.RequestInterceptResponse{}
	}
	return pluginapi.RequestInterceptResponse{
		Terminate:       true,
		StatusCode:      http.StatusForbidden,
		ResponseHeaders: http.Header{"Content-Type": {"application/json"}},
		ResponseBody:    []byte(`{"error":{"message":"Chat Completions is disabled for this API key.","type":"permission_error","code":"chat_completions_disabled"}}`),
	}
}
